version: '3'
networks:
    adata_networks:
        driver: bridge
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '123456'
    ports:
      - "5432:5432"
    networks:
      - adata_networks
  nestjs:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: '123456'
      DB_DATABASE: aspis
    networks:
      - adata_networks
